//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccFail
    {
        public long ID { get; set; }
        public Nullable<long> ScanAccID { get; set; }
        public Nullable<System.DateTime> TimeFail { get; set; }
    
        public virtual ScanAccount ScanAccount { get; set; }
    }
}
