//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinDbEntities : DbContext
    {
        public WinDbEntities()
            : base("name=WinDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccFail> AccFails { get; set; }
        public DbSet<AccScanInUse> AccScanInUses { get; set; }
        public DbSet<LoginTrace> LoginTraces { get; set; }
        public DbSet<ScanAccount> ScanAccounts { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<SystemConfig> SystemConfigs { get; set; }
    }
}
