//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanAccount
    {
        public ScanAccount()
        {
            this.AccFails = new HashSet<AccFail>();
            this.AccScanInUses = new HashSet<AccScanInUse>();
        }
    
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte ServerType { get; set; }
        public bool IsBlock { get; set; }
        public bool IsFree { get; set; }
        public int PassChangeVersion { get; set; }
    
        public virtual ICollection<AccFail> AccFails { get; set; }
        public virtual ICollection<AccScanInUse> AccScanInUses { get; set; }
    }
}
