//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AccScanInUses = new HashSet<AccScanInUse>();
            this.LoginTraces = new HashSet<LoginTrace>();
        }
    
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte Type { get; set; }
        public Nullable<byte> RouteType { get; set; }
        public Nullable<byte> AccType { get; set; }
    
        public virtual ICollection<AccScanInUse> AccScanInUses { get; set; }
        public virtual ICollection<LoginTrace> LoginTraces { get; set; }
    }
}
